name: tlio
channels:
  - pytorch
  - pytorch3d
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - pytorch
  - tabulate
  - pip
  - numpy
  - numba
  - pandas
  - scipy
  - matplotlib
  - tqdm
  - h5py
  - setuptools=69.5.1
  - nbconvert
  - pip:
    - -r requirements.txt
